# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "paddlers-shared-lib/src/schema.rs"
import_types = ["diesel::sql_types::*","crate::models::*"]
# patch_file = "paddlers-shared-lib/src/schema.patch"